CREATE SCHEMA skinni;

SELECT schema_name FROM information_schema.schemata;

-- ROLE 생성
CREATE ROLE skinni_role;

-- USER 생성 (LOGIN 권한 필요)
CREATE USER skinni_user WITH PASSWORD '1234';

-- USER를 ROLE에 할당
GRANT skinni_role TO skinni_user;



-- skinni 스키마에 대해 ROLE에게 권한 부여
GRANT USAGE ON SCHEMA skinni TO skinni_role;

-- 모든 테이블에 대해 DML + DDL 권한
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA skinni TO skinni_role;

-- 모든 시퀀스 (AUTO_INCREMENT 등)
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA skinni TO skinni_role;



ALTER DEFAULT PRIVILEGES IN SCHEMA skinni
GRANT ALL ON TABLES TO skinni_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA skinni
GRANT ALL ON SEQUENCES TO skinni_role;


-- 회사 관리
CREATE TABLE skinni.COMPANY_INFO (
     ID         VARCHAR(50)   NOT NULL,
     NAME       VARCHAR(255)  NOT NULL,
     URL        VARCHAR(255),
     CRT_USER   VARCHAR(100),
     CRTDT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     UPDT_USER  VARCHAR(100),
     UPDTDT     TIMESTAMP,
     CONSTRAINT PK_COMPANY_INFO PRIMARY KEY (ID)
);

COMMENT ON TABLE skinni.COMPANY_INFO IS '회사정보 테이블';

COMMENT ON COLUMN skinni.COMPANY_INFO.ID IS '협력회사 ID';
COMMENT ON COLUMN skinni.COMPANY_INFO.NAME IS '협력회사명';
COMMENT ON COLUMN skinni.COMPANY_INFO.URL IS '홈페이지 URL';
COMMENT ON COLUMN skinni.COMPANY_INFO.CRT_USER IS '등록자';
COMMENT ON COLUMN skinni.COMPANY_INFO.CRTDT IS '등록일시';
COMMENT ON COLUMN skinni.COMPANY_INFO.UPDT_USER IS '수정자';
COMMENT ON COLUMN skinni.COMPANY_INFO.UPDTDT IS '수정일시';

--- 제품 관리
CREATE TABLE skinni.PRODUCT_MGMT (
     ID             VARCHAR(50)    NOT NULL,
     COMPANY_ID     VARCHAR(50)    NOT NULL,
     NAME           VARCHAR(255)   NOT NULL,
     PRICE          DECIMAL(10,0)  NOT NULL DEFAULT 0,
     DESCRIPTION    TEXT,
     IMAGE_PATH     VARCHAR(255),
     COMMERCE_URL   VARCHAR(1000),
     WRINKLE        INTEGER        DEFAULT 0,
     PORE           INTEGER        DEFAULT 0,
     ELASTICITY     INTEGER        DEFAULT 0,
     MOISTURE       INTEGER        DEFAULT 0,
     CRT_USER       VARCHAR(100),
     CRTDT          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
     UPDT_USER      VARCHAR(100),
     UPDTDT         TIMESTAMP,
     CONSTRAINT PK_PRODUCT_MGMT PRIMARY KEY (ID),
     CONSTRAINT FK_PRODUCT_MGMT_01 FOREIGN KEY (COMPANY_ID)
         REFERENCES skinni.COMPANY_INFO(ID)
);

-- 테이블 설명
COMMENT ON TABLE skinni.PRODUCT_MGMT IS '제품 정보 관리 테이블';

-- 컬럼 설명
COMMENT ON COLUMN skinni.PRODUCT_MGMT.ID IS '제품 고유 ID';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.COMPANY_ID IS '회사정보 ID';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.NAME IS '제품명';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.PRICE IS '가격';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.DESCRIPTION IS '설명';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.IMAGE_PATH IS '이미지 경로';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.COMMERCE_URL IS '커머스 URL';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.WRINKLE IS '주름 (0~5의 별점)';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.PORE IS '모공 (0~5의 별점)';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.ELASTICITY IS '탄력 (0~5의 별점)';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.MOISTURE IS '수분 (0~5의 별점)';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.CRT_USER IS '등록자';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.CRTDT IS '등록일시';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.UPDT_USER IS '수정자';
COMMENT ON COLUMN skinni.PRODUCT_MGMT.UPDTDT IS '수정일시';

