version: '3.9'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: skinni_db
      POSTGRES_USER: intel_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend-net

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=skinni_db
      - DB_USER=intel_user
      - DB_PASSWORD=1234
      - DB_HOST=db
    networks:
      - backend-net

networks:
  backend-net:

